/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UyeOlRouteImport } from './routes/uye-ol'
import { Route as TurkDunyasiRouteImport } from './routes/turk-dunyasi'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SssRouteImport } from './routes/sss'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedArfRouteImport } from './routes/_authenticated/arf'
import { Route as AuthenticatedArfIndexRouteImport } from './routes/_authenticated/arf.index'
import { Route as AuthenticatedArfThreadIdRouteImport } from './routes/_authenticated/arf.$threadId'

const UyeOlRoute = UyeOlRouteImport.update({
  id: '/uye-ol',
  path: '/uye-ol',
  getParentRoute: () => rootRouteImport,
} as any)
const TurkDunyasiRoute = TurkDunyasiRouteImport.update({
  id: '/turk-dunyasi',
  path: '/turk-dunyasi',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SssRoute = SssRouteImport.update({
  id: '/sss',
  path: '/sss',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedArfRoute = AuthenticatedArfRouteImport.update({
  id: '/arf',
  path: '/arf',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArfIndexRoute = AuthenticatedArfIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedArfRoute,
} as any)
const AuthenticatedArfThreadIdRoute =
  AuthenticatedArfThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedArfRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/galeri': typeof GaleriRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sss': typeof SssRoute
  '/team': typeof TeamRoute
  '/turk-dunyasi': typeof TurkDunyasiRoute
  '/uye-ol': typeof UyeOlRoute
  '/arf': typeof AuthenticatedArfRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/tts': typeof ApiTtsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/arf/$threadId': typeof AuthenticatedArfThreadIdRoute
  '/arf/': typeof AuthenticatedArfIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/galeri': typeof GaleriRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sss': typeof SssRoute
  '/team': typeof TeamRoute
  '/turk-dunyasi': typeof TurkDunyasiRoute
  '/uye-ol': typeof UyeOlRoute
  '/api/chat': typeof ApiChatRoute
  '/api/tts': typeof ApiTtsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/arf/$threadId': typeof AuthenticatedArfThreadIdRoute
  '/arf': typeof AuthenticatedArfIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/galeri': typeof GaleriRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sss': typeof SssRoute
  '/team': typeof TeamRoute
  '/turk-dunyasi': typeof TurkDunyasiRoute
  '/uye-ol': typeof UyeOlRoute
  '/_authenticated/arf': typeof AuthenticatedArfRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/tts': typeof ApiTtsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/_authenticated/arf/$threadId': typeof AuthenticatedArfThreadIdRoute
  '/_authenticated/arf/': typeof AuthenticatedArfIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/events'
    | '/galeri'
    | '/sitemap.xml'
    | '/sss'
    | '/team'
    | '/turk-dunyasi'
    | '/uye-ol'
    | '/arf'
    | '/api/chat'
    | '/api/tts'
    | '/blog/$slug'
    | '/events/$slug'
    | '/arf/$threadId'
    | '/arf/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/events'
    | '/galeri'
    | '/sitemap.xml'
    | '/sss'
    | '/team'
    | '/turk-dunyasi'
    | '/uye-ol'
    | '/api/chat'
    | '/api/tts'
    | '/blog/$slug'
    | '/events/$slug'
    | '/arf/$threadId'
    | '/arf'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/events'
    | '/galeri'
    | '/sitemap.xml'
    | '/sss'
    | '/team'
    | '/turk-dunyasi'
    | '/uye-ol'
    | '/_authenticated/arf'
    | '/api/chat'
    | '/api/tts'
    | '/blog/$slug'
    | '/events/$slug'
    | '/_authenticated/arf/$threadId'
    | '/_authenticated/arf/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRouteWithChildren
  GaleriRoute: typeof GaleriRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SssRoute: typeof SssRoute
  TeamRoute: typeof TeamRoute
  TurkDunyasiRoute: typeof TurkDunyasiRoute
  UyeOlRoute: typeof UyeOlRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiTtsRoute: typeof ApiTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uye-ol': {
      id: '/uye-ol'
      path: '/uye-ol'
      fullPath: '/uye-ol'
      preLoaderRoute: typeof UyeOlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turk-dunyasi': {
      id: '/turk-dunyasi'
      path: '/turk-dunyasi'
      fullPath: '/turk-dunyasi'
      preLoaderRoute: typeof TurkDunyasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sss': {
      id: '/sss'
      path: '/sss'
      fullPath: '/sss'
      preLoaderRoute: typeof SssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof EventsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/arf': {
      id: '/_authenticated/arf'
      path: '/arf'
      fullPath: '/arf'
      preLoaderRoute: typeof AuthenticatedArfRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/arf/': {
      id: '/_authenticated/arf/'
      path: '/'
      fullPath: '/arf/'
      preLoaderRoute: typeof AuthenticatedArfIndexRouteImport
      parentRoute: typeof AuthenticatedArfRoute
    }
    '/_authenticated/arf/$threadId': {
      id: '/_authenticated/arf/$threadId'
      path: '/$threadId'
      fullPath: '/arf/$threadId'
      preLoaderRoute: typeof AuthenticatedArfThreadIdRouteImport
      parentRoute: typeof AuthenticatedArfRoute
    }
  }
}

interface AuthenticatedArfRouteChildren {
  AuthenticatedArfThreadIdRoute: typeof AuthenticatedArfThreadIdRoute
  AuthenticatedArfIndexRoute: typeof AuthenticatedArfIndexRoute
}

const AuthenticatedArfRouteChildren: AuthenticatedArfRouteChildren = {
  AuthenticatedArfThreadIdRoute: AuthenticatedArfThreadIdRoute,
  AuthenticatedArfIndexRoute: AuthenticatedArfIndexRoute,
}

const AuthenticatedArfRouteWithChildren =
  AuthenticatedArfRoute._addFileChildren(AuthenticatedArfRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedArfRoute: typeof AuthenticatedArfRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedArfRoute: AuthenticatedArfRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface EventsRouteChildren {
  EventsSlugRoute: typeof EventsSlugRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsSlugRoute: EventsSlugRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRouteWithChildren,
  GaleriRoute: GaleriRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SssRoute: SssRoute,
  TeamRoute: TeamRoute,
  TurkDunyasiRoute: TurkDunyasiRoute,
  UyeOlRoute: UyeOlRoute,
  ApiChatRoute: ApiChatRoute,
  ApiTtsRoute: ApiTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
